version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  jobs:
    post_install:
      - python doc/check_rtd_imports.py

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - full
