"""Generate the documentation release-notes page from CHANGELOG.md."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


RELEASE_HEADING = re.compile(r"^## \[([^\]]+)\] \(([^)]+)\)")
GENERATED_GROUP_HEADING = re.compile(r"^### ")
COMMIT_RANGE = re.compile(
    r"^\[[0-9a-f]{7,40}\]\([^)]+\)\.\.\."
    r"\[[0-9a-f]{7,40}\]\([^)]+\)$"
)
MARKDOWN_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
INLINE_CODE = re.compile(r"(?<!`)`([^`]+)`(?!`)")
BULLET_LINE = re.compile(r"^\s*[-*]\s+(.+)")
ORDERED_LIST_LINE = re.compile(r"^\s*(\d+\.\s+.+)")


@dataclass
class ReleaseNote:
    """Release notes extracted from one changelog release section."""

    version: str
    date: str
    lines: list[str]


def markdown_to_rst(text: str) -> str:
    """Convert the small Markdown subset used in release notes to reST."""
    text = INLINE_CODE.sub(r"``\1``", text)
    text = MARKDOWN_LINK.sub(r"`\1 <\2>`_", text)
    return text.replace(r"\...", "...")


def strip_outer_blank_lines(lines: list[str]) -> list[str]:
    """Remove leading and trailing blank lines from ``lines``."""
    start = 0
    end = len(lines)
    while start < end and not lines[start].strip():
        start += 1
    while end > start and not lines[end - 1].strip():
        end -= 1
    return lines[start:end]


def normalize_note_lines(lines: list[str]) -> list[str]:
    """Normalize Markdown-style wrapped notes into simple reST lines."""
    normalized: list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if normalized and normalized[-1] != "":
                normalized.append("")
            continue

        bullet = BULLET_LINE.match(line)
        ordered = ORDERED_LIST_LINE.match(line)
        if bullet:
            normalized.append(f"- {bullet.group(1)}")
        elif ordered:
            normalized.append(ordered.group(1))
        elif normalized and normalized[-1]:
            normalized[-1] = f"{normalized[-1]} {stripped}"
        else:
            normalized.append(stripped)

    return strip_outer_blank_lines(normalized)


def extract_release_notes(changelog: str) -> list[ReleaseNote]:
    """Extract manually written release notes from ``CHANGELOG.md``."""
    releases: list[ReleaseNote] = []
    current_version: str | None = None
    current_date: str | None = None
    current_lines: list[str] = []
    in_release_notes = False

    def flush_current() -> None:
        nonlocal current_lines
        if current_version is None or current_date is None:
            return
        notes = normalize_note_lines(strip_outer_blank_lines(current_lines))
        if notes:
            releases.append(
                ReleaseNote(
                    version=current_version,
                    date=current_date,
                    lines=[markdown_to_rst(line) for line in notes],
                )
            )
        current_lines = []

    for raw_line in changelog.splitlines():
        heading = RELEASE_HEADING.match(raw_line)
        if heading:
            flush_current()
            current_version = heading.group(1)
            current_date = heading.group(2)
            current_lines = []
            in_release_notes = True
            continue

        if current_version is None:
            continue

        if raw_line.startswith("## "):
            flush_current()
            current_version = None
            current_date = None
            in_release_notes = False
            continue

        if GENERATED_GROUP_HEADING.match(raw_line):
            in_release_notes = False
            continue

        if not in_release_notes or COMMIT_RANGE.match(raw_line):
            continue

        current_lines.append(raw_line)

    flush_current()
    return releases


def render_release_notes(releases: list[ReleaseNote]) -> str:
    """Render release notes as a Sphinx-friendly reST document."""
    lines = [
        "Release Notes",
        "=============",
        "",
        ".. This file is generated by doc/generate_release_notes.py from",
        "   CHANGELOG.md. Do not edit it by hand.",
        "",
    ]

    for release in releases:
        title = f"{release.version} ({release.date})"
        lines.extend([title, "-" * len(title), ""])
        lines.extend(release.lines)
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    """Generate ``doc/source/release_notes.rst``."""
    repo_root = Path(__file__).resolve().parents[1]
    changelog_path = repo_root / "CHANGELOG.md"
    output_path = repo_root / "doc" / "source" / "release_notes.rst"

    releases = extract_release_notes(changelog_path.read_text(encoding="utf-8"))
    output_path.write_text(render_release_notes(releases), encoding="utf-8")


if __name__ == "__main__":
    main()
